# Generated by Django 5.2.14 on 2026-06-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipazon', '0002_cartmodel_ordermodel_reviewmodel_wishlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
