# Generated by Django 5.2.14 on 2026-06-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipazon', '0004_ordermodel_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='pimage1',
            new_name='pimage1_url',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pimage2',
            new_name='pimage2_url',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pimage1_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pimage2_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pimage_type1',
            field=models.CharField(default='link', max_length=10),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pimage_type2',
            field=models.CharField(default='link', max_length=10),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='upi_qr_file',
            field=models.ImageField(blank=True, null=True, upload_to='upi_qrs/'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='upi_qr_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
